spring:
  datasource:
    url: jdbc:h2:mem:kbtgBoot
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
              sql:
                BasicBinder: TRACE